# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tku_msgs/AllLineData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tku_msgs.msg

class AllLineData(genpy.Message):
  _md5sum = "c89c4722901f5abc77d01bb5fa2b88a2"
  _type = "tku_msgs/AllLineData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """LineData[] all_LineData

================================================================================
MSG: tku_msgs/LineData
float32 Line_theta
int16 Line_length
Cooridinate start_point
Cooridinate end_point
Cooridinate center_point
float32 relative_distance
Cooridinate Nearest_point

================================================================================
MSG: tku_msgs/Cooridinate
int16 x
int16 y
"""
  __slots__ = ['all_LineData']
  _slot_types = ['tku_msgs/LineData[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       all_LineData

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AllLineData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.all_LineData is None:
        self.all_LineData = []
    else:
      self.all_LineData = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.all_LineData)
      buff.write(_struct_I.pack(length))
      for val1 in self.all_LineData:
        _x = val1
        buff.write(_get_struct_fh().pack(_x.Line_theta, _x.Line_length))
        _v1 = val1.start_point
        _x = _v1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
        _v2 = val1.end_point
        _x = _v2
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
        _v3 = val1.center_point
        _x = _v3
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
        _x = val1.relative_distance
        buff.write(_get_struct_f().pack(_x))
        _v4 = val1.Nearest_point
        _x = _v4
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.all_LineData is None:
        self.all_LineData = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.all_LineData = []
      for i in range(0, length):
        val1 = tku_msgs.msg.LineData()
        _x = val1
        start = end
        end += 6
        (_x.Line_theta, _x.Line_length,) = _get_struct_fh().unpack(str[start:end])
        _v5 = val1.start_point
        _x = _v5
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        _v6 = val1.end_point
        _x = _v6
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        _v7 = val1.center_point
        _x = _v7
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        start = end
        end += 4
        (val1.relative_distance,) = _get_struct_f().unpack(str[start:end])
        _v8 = val1.Nearest_point
        _x = _v8
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.all_LineData.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.all_LineData)
      buff.write(_struct_I.pack(length))
      for val1 in self.all_LineData:
        _x = val1
        buff.write(_get_struct_fh().pack(_x.Line_theta, _x.Line_length))
        _v9 = val1.start_point
        _x = _v9
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
        _v10 = val1.end_point
        _x = _v10
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
        _v11 = val1.center_point
        _x = _v11
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
        _x = val1.relative_distance
        buff.write(_get_struct_f().pack(_x))
        _v12 = val1.Nearest_point
        _x = _v12
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.all_LineData is None:
        self.all_LineData = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.all_LineData = []
      for i in range(0, length):
        val1 = tku_msgs.msg.LineData()
        _x = val1
        start = end
        end += 6
        (_x.Line_theta, _x.Line_length,) = _get_struct_fh().unpack(str[start:end])
        _v13 = val1.start_point
        _x = _v13
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        _v14 = val1.end_point
        _x = _v14
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        _v15 = val1.center_point
        _x = _v15
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        start = end
        end += 4
        (val1.relative_distance,) = _get_struct_f().unpack(str[start:end])
        _v16 = val1.Nearest_point
        _x = _v16
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.all_LineData.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
_struct_fh = None
def _get_struct_fh():
    global _struct_fh
    if _struct_fh is None:
        _struct_fh = struct.Struct("<fh")
    return _struct_fh
