# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tku_msgs/LineData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tku_msgs.msg

class LineData(genpy.Message):
  _md5sum = "286db25d85b96a7f73924a86b3c7e511"
  _type = "tku_msgs/LineData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 Line_theta
int16 Line_length
Cooridinate start_point
Cooridinate end_point
Cooridinate center_point
float32 relative_distance
Cooridinate Nearest_point

================================================================================
MSG: tku_msgs/Cooridinate
int16 x
int16 y
"""
  __slots__ = ['Line_theta','Line_length','start_point','end_point','center_point','relative_distance','Nearest_point']
  _slot_types = ['float32','int16','tku_msgs/Cooridinate','tku_msgs/Cooridinate','tku_msgs/Cooridinate','float32','tku_msgs/Cooridinate']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Line_theta,Line_length,start_point,end_point,center_point,relative_distance,Nearest_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LineData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Line_theta is None:
        self.Line_theta = 0.
      if self.Line_length is None:
        self.Line_length = 0
      if self.start_point is None:
        self.start_point = tku_msgs.msg.Cooridinate()
      if self.end_point is None:
        self.end_point = tku_msgs.msg.Cooridinate()
      if self.center_point is None:
        self.center_point = tku_msgs.msg.Cooridinate()
      if self.relative_distance is None:
        self.relative_distance = 0.
      if self.Nearest_point is None:
        self.Nearest_point = tku_msgs.msg.Cooridinate()
    else:
      self.Line_theta = 0.
      self.Line_length = 0
      self.start_point = tku_msgs.msg.Cooridinate()
      self.end_point = tku_msgs.msg.Cooridinate()
      self.center_point = tku_msgs.msg.Cooridinate()
      self.relative_distance = 0.
      self.Nearest_point = tku_msgs.msg.Cooridinate()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f7hf2h().pack(_x.Line_theta, _x.Line_length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y, _x.relative_distance, _x.Nearest_point.x, _x.Nearest_point.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_point is None:
        self.start_point = tku_msgs.msg.Cooridinate()
      if self.end_point is None:
        self.end_point = tku_msgs.msg.Cooridinate()
      if self.center_point is None:
        self.center_point = tku_msgs.msg.Cooridinate()
      if self.Nearest_point is None:
        self.Nearest_point = tku_msgs.msg.Cooridinate()
      end = 0
      _x = self
      start = end
      end += 26
      (_x.Line_theta, _x.Line_length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y, _x.relative_distance, _x.Nearest_point.x, _x.Nearest_point.y,) = _get_struct_f7hf2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f7hf2h().pack(_x.Line_theta, _x.Line_length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y, _x.relative_distance, _x.Nearest_point.x, _x.Nearest_point.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_point is None:
        self.start_point = tku_msgs.msg.Cooridinate()
      if self.end_point is None:
        self.end_point = tku_msgs.msg.Cooridinate()
      if self.center_point is None:
        self.center_point = tku_msgs.msg.Cooridinate()
      if self.Nearest_point is None:
        self.Nearest_point = tku_msgs.msg.Cooridinate()
      end = 0
      _x = self
      start = end
      end += 26
      (_x.Line_theta, _x.Line_length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y, _x.relative_distance, _x.Nearest_point.x, _x.Nearest_point.y,) = _get_struct_f7hf2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f7hf2h = None
def _get_struct_f7hf2h():
    global _struct_f7hf2h
    if _struct_f7hf2h is None:
        _struct_f7hf2h = struct.Struct("<f7hf2h")
    return _struct_f7hf2h
