// Generated by gencpp from file tku_msgs/BGRInfo.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_BGRINFO_H
#define TKU_MSGS_MESSAGE_BGRINFO_H

#include <ros/service_traits.h>


#include <tku_msgs/BGRInfoRequest.h>
#include <tku_msgs/BGRInfoResponse.h>


namespace tku_msgs
{

struct BGRInfo
{

typedef BGRInfoRequest Request;
typedef BGRInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BGRInfo
} // namespace tku_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tku_msgs::BGRInfo > {
  static const char* value()
  {
    return "b03a10dbd390a3bc71ab9139e41340a6";
  }

  static const char* value(const ::tku_msgs::BGRInfo&) { return value(); }
};

template<>
struct DataType< ::tku_msgs::BGRInfo > {
  static const char* value()
  {
    return "tku_msgs/BGRInfo";
  }

  static const char* value(const ::tku_msgs::BGRInfo&) { return value(); }
};


// service_traits::MD5Sum< ::tku_msgs::BGRInfoRequest> should match
// service_traits::MD5Sum< ::tku_msgs::BGRInfo >
template<>
struct MD5Sum< ::tku_msgs::BGRInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::BGRInfo >::value();
  }
  static const char* value(const ::tku_msgs::BGRInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::BGRInfoRequest> should match
// service_traits::DataType< ::tku_msgs::BGRInfo >
template<>
struct DataType< ::tku_msgs::BGRInfoRequest>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::BGRInfo >::value();
  }
  static const char* value(const ::tku_msgs::BGRInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tku_msgs::BGRInfoResponse> should match
// service_traits::MD5Sum< ::tku_msgs::BGRInfo >
template<>
struct MD5Sum< ::tku_msgs::BGRInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::BGRInfo >::value();
  }
  static const char* value(const ::tku_msgs::BGRInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::BGRInfoResponse> should match
// service_traits::DataType< ::tku_msgs::BGRInfo >
template<>
struct DataType< ::tku_msgs::BGRInfoResponse>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::BGRInfo >::value();
  }
  static const char* value(const ::tku_msgs::BGRInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKU_MSGS_MESSAGE_BGRINFO_H
