// Generated by gencpp from file tku_msgs/BGRInfoResponse.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_BGRINFORESPONSE_H
#define TKU_MSGS_MESSAGE_BGRINFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct BGRInfoResponse_
{
  typedef BGRInfoResponse_<ContainerAllocator> Type;

  BGRInfoResponse_()
    : BValue(0)
    , GValue(0)
    , RValue(0)  {
    }
  BGRInfoResponse_(const ContainerAllocator& _alloc)
    : BValue(0)
    , GValue(0)
    , RValue(0)  {
  (void)_alloc;
    }



   typedef int32_t _BValue_type;
  _BValue_type BValue;

   typedef int32_t _GValue_type;
  _GValue_type GValue;

   typedef int32_t _RValue_type;
  _RValue_type RValue;





  typedef boost::shared_ptr< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BGRInfoResponse_

typedef ::tku_msgs::BGRInfoResponse_<std::allocator<void> > BGRInfoResponse;

typedef boost::shared_ptr< ::tku_msgs::BGRInfoResponse > BGRInfoResponsePtr;
typedef boost::shared_ptr< ::tku_msgs::BGRInfoResponse const> BGRInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::BGRInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::BGRInfoResponse_<ContainerAllocator1> & lhs, const ::tku_msgs::BGRInfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.BValue == rhs.BValue &&
    lhs.GValue == rhs.GValue &&
    lhs.RValue == rhs.RValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::BGRInfoResponse_<ContainerAllocator1> & lhs, const ::tku_msgs::BGRInfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa6d7a5ece2eb227aec780feb59082f5";
  }

  static const char* value(const ::tku_msgs::BGRInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa6d7a5ece2eb227ULL;
  static const uint64_t static_value2 = 0xaec780feb59082f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/BGRInfoResponse";
  }

  static const char* value(const ::tku_msgs::BGRInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 BValue\n"
"int32 GValue\n"
"int32 RValue\n"
"\n"
;
  }

  static const char* value(const ::tku_msgs::BGRInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BValue);
      stream.next(m.GValue);
      stream.next(m.RValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BGRInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::BGRInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::BGRInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "BValue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BValue);
    s << indent << "GValue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.GValue);
    s << indent << "RValue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.RValue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_BGRINFORESPONSE_H
