// Generated by gencpp from file tku_msgs/GetVelocity.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_GETVELOCITY_H
#define TKU_MSGS_MESSAGE_GETVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct GetVelocity_
{
  typedef GetVelocity_<ContainerAllocator> Type;

  GetVelocity_()
    : x(0)
    , y(0)
    , thta(0)  {
    }
  GetVelocity_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , thta(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _thta_type;
  _thta_type thta;





  typedef boost::shared_ptr< ::tku_msgs::GetVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::GetVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct GetVelocity_

typedef ::tku_msgs::GetVelocity_<std::allocator<void> > GetVelocity;

typedef boost::shared_ptr< ::tku_msgs::GetVelocity > GetVelocityPtr;
typedef boost::shared_ptr< ::tku_msgs::GetVelocity const> GetVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::GetVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::GetVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::GetVelocity_<ContainerAllocator1> & lhs, const ::tku_msgs::GetVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.thta == rhs.thta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::GetVelocity_<ContainerAllocator1> & lhs, const ::tku_msgs::GetVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::GetVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::GetVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::GetVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::GetVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::GetVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::GetVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::GetVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "608e030db4b1da323a9f83bf257ec356";
  }

  static const char* value(const ::tku_msgs::GetVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x608e030db4b1da32ULL;
  static const uint64_t static_value2 = 0x3a9f83bf257ec356ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::GetVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/GetVelocity";
  }

  static const char* value(const ::tku_msgs::GetVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::GetVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 thta\n"
;
  }

  static const char* value(const ::tku_msgs::GetVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::GetVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.thta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::GetVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::GetVelocity_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "thta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.thta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_GETVELOCITY_H
