// Generated by gencpp from file tku_msgs/HoughInfo.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_HOUGHINFO_H
#define TKU_MSGS_MESSAGE_HOUGHINFO_H

#include <ros/service_traits.h>


#include <tku_msgs/HoughInfoRequest.h>
#include <tku_msgs/HoughInfoResponse.h>


namespace tku_msgs
{

struct HoughInfo
{

typedef HoughInfoRequest Request;
typedef HoughInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HoughInfo
} // namespace tku_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tku_msgs::HoughInfo > {
  static const char* value()
  {
    return "8863b4634d224e62b8e462b542f70e71";
  }

  static const char* value(const ::tku_msgs::HoughInfo&) { return value(); }
};

template<>
struct DataType< ::tku_msgs::HoughInfo > {
  static const char* value()
  {
    return "tku_msgs/HoughInfo";
  }

  static const char* value(const ::tku_msgs::HoughInfo&) { return value(); }
};


// service_traits::MD5Sum< ::tku_msgs::HoughInfoRequest> should match
// service_traits::MD5Sum< ::tku_msgs::HoughInfo >
template<>
struct MD5Sum< ::tku_msgs::HoughInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::HoughInfo >::value();
  }
  static const char* value(const ::tku_msgs::HoughInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::HoughInfoRequest> should match
// service_traits::DataType< ::tku_msgs::HoughInfo >
template<>
struct DataType< ::tku_msgs::HoughInfoRequest>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::HoughInfo >::value();
  }
  static const char* value(const ::tku_msgs::HoughInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tku_msgs::HoughInfoResponse> should match
// service_traits::MD5Sum< ::tku_msgs::HoughInfo >
template<>
struct MD5Sum< ::tku_msgs::HoughInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::HoughInfo >::value();
  }
  static const char* value(const ::tku_msgs::HoughInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::HoughInfoResponse> should match
// service_traits::DataType< ::tku_msgs::HoughInfo >
template<>
struct DataType< ::tku_msgs::HoughInfoResponse>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::HoughInfo >::value();
  }
  static const char* value(const ::tku_msgs::HoughInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKU_MSGS_MESSAGE_HOUGHINFO_H
