// Generated by gencpp from file tku_msgs/HoughValue.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_HOUGHVALUE_H
#define TKU_MSGS_MESSAGE_HOUGHVALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct HoughValue_
{
  typedef HoughValue_<ContainerAllocator> Type;

  HoughValue_()
    : Hough_threshold(0)
    , Hough_minLineLength(0)
    , Hough_maxLineGap(0)  {
    }
  HoughValue_(const ContainerAllocator& _alloc)
    : Hough_threshold(0)
    , Hough_minLineLength(0)
    , Hough_maxLineGap(0)  {
  (void)_alloc;
    }



   typedef int16_t _Hough_threshold_type;
  _Hough_threshold_type Hough_threshold;

   typedef int16_t _Hough_minLineLength_type;
  _Hough_minLineLength_type Hough_minLineLength;

   typedef int16_t _Hough_maxLineGap_type;
  _Hough_maxLineGap_type Hough_maxLineGap;





  typedef boost::shared_ptr< ::tku_msgs::HoughValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::HoughValue_<ContainerAllocator> const> ConstPtr;

}; // struct HoughValue_

typedef ::tku_msgs::HoughValue_<std::allocator<void> > HoughValue;

typedef boost::shared_ptr< ::tku_msgs::HoughValue > HoughValuePtr;
typedef boost::shared_ptr< ::tku_msgs::HoughValue const> HoughValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::HoughValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::HoughValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::HoughValue_<ContainerAllocator1> & lhs, const ::tku_msgs::HoughValue_<ContainerAllocator2> & rhs)
{
  return lhs.Hough_threshold == rhs.Hough_threshold &&
    lhs.Hough_minLineLength == rhs.Hough_minLineLength &&
    lhs.Hough_maxLineGap == rhs.Hough_maxLineGap;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::HoughValue_<ContainerAllocator1> & lhs, const ::tku_msgs::HoughValue_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::HoughValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::HoughValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::HoughValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::HoughValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::HoughValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::HoughValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::HoughValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d05e92877df6915f3edc27ac041474d7";
  }

  static const char* value(const ::tku_msgs::HoughValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd05e92877df6915fULL;
  static const uint64_t static_value2 = 0x3edc27ac041474d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::HoughValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/HoughValue";
  }

  static const char* value(const ::tku_msgs::HoughValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::HoughValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 Hough_threshold\n"
"int16 Hough_minLineLength\n"
"int16 Hough_maxLineGap\n"
"\n"
"\n"
;
  }

  static const char* value(const ::tku_msgs::HoughValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::HoughValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Hough_threshold);
      stream.next(m.Hough_minLineLength);
      stream.next(m.Hough_maxLineGap);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HoughValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::HoughValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::HoughValue_<ContainerAllocator>& v)
  {
    s << indent << "Hough_threshold: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Hough_threshold);
    s << indent << "Hough_minLineLength: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Hough_minLineLength);
    s << indent << "Hough_maxLineGap: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Hough_maxLineGap);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_HOUGHVALUE_H
