// Generated by gencpp from file tku_msgs/LineData.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_LINEDATA_H
#define TKU_MSGS_MESSAGE_LINEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tku_msgs/Cooridinate.h>
#include <tku_msgs/Cooridinate.h>
#include <tku_msgs/Cooridinate.h>
#include <tku_msgs/Cooridinate.h>

namespace tku_msgs
{
template <class ContainerAllocator>
struct LineData_
{
  typedef LineData_<ContainerAllocator> Type;

  LineData_()
    : Line_theta(0.0)
    , Line_length(0)
    , start_point()
    , end_point()
    , center_point()
    , relative_distance(0.0)
    , Nearest_point()  {
    }
  LineData_(const ContainerAllocator& _alloc)
    : Line_theta(0.0)
    , Line_length(0)
    , start_point(_alloc)
    , end_point(_alloc)
    , center_point(_alloc)
    , relative_distance(0.0)
    , Nearest_point(_alloc)  {
  (void)_alloc;
    }



   typedef float _Line_theta_type;
  _Line_theta_type Line_theta;

   typedef int16_t _Line_length_type;
  _Line_length_type Line_length;

   typedef  ::tku_msgs::Cooridinate_<ContainerAllocator>  _start_point_type;
  _start_point_type start_point;

   typedef  ::tku_msgs::Cooridinate_<ContainerAllocator>  _end_point_type;
  _end_point_type end_point;

   typedef  ::tku_msgs::Cooridinate_<ContainerAllocator>  _center_point_type;
  _center_point_type center_point;

   typedef float _relative_distance_type;
  _relative_distance_type relative_distance;

   typedef  ::tku_msgs::Cooridinate_<ContainerAllocator>  _Nearest_point_type;
  _Nearest_point_type Nearest_point;





  typedef boost::shared_ptr< ::tku_msgs::LineData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::LineData_<ContainerAllocator> const> ConstPtr;

}; // struct LineData_

typedef ::tku_msgs::LineData_<std::allocator<void> > LineData;

typedef boost::shared_ptr< ::tku_msgs::LineData > LineDataPtr;
typedef boost::shared_ptr< ::tku_msgs::LineData const> LineDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::LineData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::LineData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::LineData_<ContainerAllocator1> & lhs, const ::tku_msgs::LineData_<ContainerAllocator2> & rhs)
{
  return lhs.Line_theta == rhs.Line_theta &&
    lhs.Line_length == rhs.Line_length &&
    lhs.start_point == rhs.start_point &&
    lhs.end_point == rhs.end_point &&
    lhs.center_point == rhs.center_point &&
    lhs.relative_distance == rhs.relative_distance &&
    lhs.Nearest_point == rhs.Nearest_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::LineData_<ContainerAllocator1> & lhs, const ::tku_msgs::LineData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::LineData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::LineData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::LineData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::LineData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::LineData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::LineData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::LineData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "286db25d85b96a7f73924a86b3c7e511";
  }

  static const char* value(const ::tku_msgs::LineData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x286db25d85b96a7fULL;
  static const uint64_t static_value2 = 0x73924a86b3c7e511ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::LineData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/LineData";
  }

  static const char* value(const ::tku_msgs::LineData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::LineData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Line_theta\n"
"int16 Line_length\n"
"Cooridinate start_point\n"
"Cooridinate end_point\n"
"Cooridinate center_point\n"
"float32 relative_distance\n"
"Cooridinate Nearest_point\n"
"\n"
"================================================================================\n"
"MSG: tku_msgs/Cooridinate\n"
"int16 x\n"
"int16 y\n"
;
  }

  static const char* value(const ::tku_msgs::LineData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::LineData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Line_theta);
      stream.next(m.Line_length);
      stream.next(m.start_point);
      stream.next(m.end_point);
      stream.next(m.center_point);
      stream.next(m.relative_distance);
      stream.next(m.Nearest_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::LineData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::LineData_<ContainerAllocator>& v)
  {
    s << indent << "Line_theta: ";
    Printer<float>::stream(s, indent + "  ", v.Line_theta);
    s << indent << "Line_length: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Line_length);
    s << indent << "start_point: ";
    s << std::endl;
    Printer< ::tku_msgs::Cooridinate_<ContainerAllocator> >::stream(s, indent + "  ", v.start_point);
    s << indent << "end_point: ";
    s << std::endl;
    Printer< ::tku_msgs::Cooridinate_<ContainerAllocator> >::stream(s, indent + "  ", v.end_point);
    s << indent << "center_point: ";
    s << std::endl;
    Printer< ::tku_msgs::Cooridinate_<ContainerAllocator> >::stream(s, indent + "  ", v.center_point);
    s << indent << "relative_distance: ";
    Printer<float>::stream(s, indent + "  ", v.relative_distance);
    s << indent << "Nearest_point: ";
    s << std::endl;
    Printer< ::tku_msgs::Cooridinate_<ContainerAllocator> >::stream(s, indent + "  ", v.Nearest_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_LINEDATA_H
